### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by KFishner** [tasdikrahman/terraform-google-network#1]
Hey there! Can you update your repo name to "terraform-google-network"? That's the official naming for Google modules which matches the naming of the [Terraform Google provider](https://www.terraform.io/docs/providers/google/index.html). 

That way your modules will show up with the verified Google modules when users search: https://registry.terraform.io/browse?provider=google

For reference here is how the repo name is used to create the module name in the TF Registry:
https://www.terraform.io/docs/registry/modules/publish.html

**Comment by tasdikrahman** [comment]
@KFishner Done. Would I need to change anything else from my side for the newer name to reflect on the registry?

**Comment by KFishner** [comment]
@tasdikrahman awesome. I think you'll need to cut a new version so that the Registry ingresses the change

**Comment by tasdikrahman** [comment]
Changed.
